# services:
#   next_app:
#     depends_on:
#       - mongodb
#     env_file:
#       - .env
#   mongodb:
#     image: mongo
#     ports:
#       - "27017:27017"
#     restart: always
#     volumes:
#       - mongodb_data:/data/db
#     env_file:
#       - .env

# volumes:
#   mongodb_data:

services:
  next_app:
    depends_on:
      mongodb:
        condition: service_healthy # Wait for MongoDB to be healthy
    env_file:
      - .env
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
# services:
#   next_app:
#     image: your-app-image
#     deploy:
#       replicas: 4
#       update_config:
#         parallelism: 2
#         delay: 10s
#       restart_policy:
#         condition: on-failure
#     depends_on:
#       mongodb:
#         condition: service_healthy
#     env_file:
#       - .env
#     networks:
#       - app-network

#   mongodb:
#     image: mongo
#     ports:
#       - "27017:27017"
#     restart: always
#     volumes:
#       - mongodb_data:/data/db
#     env_file:
#       - .env
#     healthcheck:
#       test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
#       interval: 10s
#       timeout: 10s
#       retries: 3
#     networks:
#       - app-network

# volumes:
#   mongodb_data:

# networks:
#   app-network:
